### ISSUE TITLE
Boundary condition mishap in feltorSesol

### ISSUE THREAD

**Issue by rkube** [feltor-dev/feltor#10]
I'm running the feltorSesol code with the following input.json:
{
    "n" :  3,       //# x-y-polynomials
    "Nx" : 224,     //# grid points in x
    "Ny" : 224,     //# grid points in y
    "dt" : 0.0125,     //time step in units of c_s/rho_s
    "n_out"  : 3,   //# x-y polynomials in output
    "Nx_out" : 224, //# grid points in x in output fields
    "Ny_out" : 224, //# grid points in y in output fields
    "itstp"  : 1000,   //steps between outputs
    "maxout" : 1000, //# outputs excluding first
    "eps_pol"   : 1e-5,   //accuracy of polarisation solver
    "eps_gamma" : 1e-6,   //accuracy of Gamma 
    "eps_time"  : 1e-12,  //accuracy of implicit time-stepper
    "mu_e"      : -0.000272121, // -m_e/m_i zb (-0.000544617,-0.000272121,-0.000181372 )
    "curvature" : 1.5e-4,   //magnetic curvature
    "tau"       : 1.0,      //Ti/Te
    "nu_perp"   : 2.5e-3,   //pependicular viscosity
    "D"         : 5.0e-11,   //coupling (D ~ curvature^2)
    "C"         : 2.5e-6,   //Parallel Resistivity (~D lx/d)        
    "l_para"    : 1e6 ,     //parallel Length (~ 2 pi q / mcv)
    "amplitude" : 2.5e-2,      //amplitude of the blob
    "sigma"  : 2.5,          //blob variance in units of rho_s
    "posX"  : 0.3333,          //blob x-position in units of lx
    "posY"  : 0.5,          //blob y-position in units of ly
    "prof_amp": 4.0,        //Profile amplitude
    "bg_prof_amp" : 1.0,    //Background Prof amplitude 
    "lx"  : 200,            //lx in units of rho_s
    "ly"  : 200,            //ly in units of rho_s
    "bc_x"    : "DIR_NEU",        //boundary condition in x
    "bc_y"    : "PER",        //boundary condition in y
    "bc_x_pot": "DIR_NEU",        //boundary condition in x for phi
    "hwmode": 1,            // ordinary/modified HW (0/1)
    "ln": 100,              //gradient length (in rho_s) 
    "SOL_b" : 0.3,     //SOL boundary in units of lx (>1 no SOL)
    "prof_source_rate" : 0.1 , //profile source rate in units c_s/rho_s
    "source_b" : 0.1666666,    //source dampingb in u of lx (<1 no Source) 
    "source_damping_width" : 0.5,  //sink, sol and edge damping width
    "prof_sink_rate" : 0.1 , //profile source rate in units c_s/rho_s
    "sink_b" : 0.8,    //sink dampingb in u of lx (<1 no Source) 
    "damping_width" : 0.5  //source, sink, sol and edge damping width
    "fluxmode" : 0     // "gradient" driven (0), flux driven (1)
}

It throws an error:
-bash-4.1$ ./feltor_mpi input.json out.nc
terminate called after throwing an instance of 'dg::Ooops'
  what():  No matching boundary condition!

Any ideas?

**Comment by mrheld** [comment]
change bc_x_pot to bc_x_phi
